export { default as Navbar } from "./navbar";
export { default as Footer } from "./footer";
export { default as Carousel } from "./carousel";
export { default as Modals } from "./modals";
export { default as Home } from "../pages/home";
export { default as Articles } from "../pages/articles";
export { default as About } from "../pages/about";
export { default as Booking } from "../pages/booking";
export { default as Admin } from "../pages/admin";
export { default as c1 } from "../images/carousel1.png";
export { default as c2 } from "../images/carousel2.png";
export { default as c3 } from "../images/carousel3.png";
export { default as a1 } from "../images/1.png";
export { default as a2 } from "../images/2.png";
export { default as a3 } from "../images/3.png";
export { default as abp } from "../images/aboutpage.png";
export { default as artcl1 } from "../images/articles page.png";
export { default as artcl2 } from "../images/articles page2.png";
export { default as artcl3 } from "../images/articles page3.png";
export { default as artcl4 } from "../images/articles page4.png";
export { default as artemisLogoPNG } from "../images/Artemis logo.png";
export { default as artemisLogoSVG } from "../images/Artemis Logo.svg";
export { default as artemisFinalPNG } from "../images/ARTEMISFinal.png";
export { default as artemisLogoDark } from "../images/ARTEMISlogoDark.ico";
export { default as artemisLogoDarkPNG } from "../images/ARTEMISlogoDark.png";
export { default as bdo } from "../images/BDO.png";
export { default as emrgncyC } from "../images/emergency-contraception-infographic.png";
export { default as gcash } from "../images/Gcash.png";
export { default as paymaya } from "../images/paymaya.png";
export { default as paypal } from "../images/PayPal.png";
export { default as perf } from "../images/perfectly imperfect info.jpg";
export { default as robinson } from "../images/robinsonsbank.png";
export { default as sample } from "../images/sampleIMG.svg";